In [17]:
# Create a vector
v <- c(5, 10, 15, 20, 25)
print(v)

[1]  5 10 15 20 25


In [6]:
m <- matrix(1:6, nrow=2, ncol=3)
print(m)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [ ]:
m <- matrix(1:6, nrow=3, ncol=3)
print(m)

# We get an error because the number of elements in the matrix (6) does not match the number of elements needed to fill a 3x3 matrix (9)

Warning message in matrix(1:6, nrow = 3, ncol = 3):
"data length differs from size of matrix: [6 != 3 x 3]"


     [,1] [,2] [,3]
[1,]    1    4    1
[2,]    2    5    2
[3,]    3    6    3


In [8]:
print(m[2,3])

m[1,2] <- 99
print(m)

[1] 6
     [,1] [,2] [,3]
[1,]    1   99    5
[2,]    2    4    6


In [1]:
a <- matrix(c(1, 2, 3, 4), nrow=2)
b <- matrix(c(2, 0, 1, 3), nrow=2)

print(a)
print(b)

result <- a %*% b
print(result)

     [,1] [,2]
[1,]    1    3
[2,]    2    4
     [,1] [,2]
[1,]    2    1
[2,]    0    3
     [,1] [,2]
[1,]    2   10
[2,]    4   14


In [ ]:
# changing one value in b changed the result of the matrix multiplication in col 1, col 2 is the same as before, but col 1 is different because of the change in b[1,2] from 0 to 4
a <- matrix(c(1, 2, 3, 4), nrow=2)
b <- matrix(c(2, 4, 1, 3), nrow=2)

result <- a %*% b
print(result)

     [,1] [,2]
[1,]   14   10
[2,]   20   14
